### ISSUE TITLE
Library won't load, and can't upload.

### ISSUE THREAD

**Issue by ranestav** [SteamGridDB/steamgriddb-manager#123]
When I open steamgriddb, I get an infinite loading circle in the library tab.  When I go to the import tab, I can see games there but when I click import nothing happens.
![steamgriddb bug](https://user-images.githubusercontent.com/56719466/106929135-9ba2b480-66d9-11eb-8fd6-9bbcfc6f464f.png)
![steamgriddb bug1](https://user-images.githubusercontent.com/56719466/106929147-9e050e80-66d9-11eb-88c3-e675a8e76481.png)

**Comment by kongomongo** [comment]
What does your log file say? Its usually located in %APPDATA%\Electron\log.log

**Comment by Juanitocancino** [comment]
> What does your log file say? Its usually located in %APPDATA%\Electron\log.log

I Have the same issue... I pass the logs of this similar problem (Don't load library, but i can import games)
i have the version 0.4.2 ( my logs were in `%APPDATA%\steamgriddb-manager` on Windows 10 1909 (if you wanted or replay to this i can open another issue or we can use this thread)

LOG:

[2021-06-30 20:45:43.639] [info] Started SGDB Manager 0.4.2
[2021-06-30 20:45:44.733] [info] Got Steam path: c:/program files (x86)/steam
[2021-06-30 20:45:44.743] [info] Got Steam user: 81978887
[2021-06-30 20:45:44.755] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
[2021-06-30 20:47:06.575] [info] Import: Started bnet
[2021-06-30 20:47:06.633] [info] Import: Completed bnet
[2021-06-30 20:47:06.634] [info] Import: Started gog
[2021-06-30 20:47:06.825] [info] Import: Completed gog
[2021-06-30 20:47:06.826] [info] Import: Started origin
[2021-06-30 20:47:08.062] [info] Import: Completed origin
[2021-06-30 20:47:08.063] [info] Import: Started uplay
[2021-06-30 20:47:08.279] [info] Import: uplay rejected Error: Could not parse YAML
[2021-06-30 20:47:17.173] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
[2021-06-30 20:47:32.582] [info] Import: Started bnet
[2021-06-30 20:47:32.638] [info] Import: Completed bnet
[2021-06-30 20:47:32.639] [info] Import: Started gog
[2021-06-30 20:47:32.828] [info] Import: Completed gog
[2021-06-30 20:47:32.829] [info] Import: Started origin
[2021-06-30 20:47:33.891] [info] Import: Completed origin
[2021-06-30 20:47:33.892] [info] Import: Started uplay
[2021-06-30 20:47:34.111] [info] Import: uplay rejected Error: Could not parse YAML
[2021-06-30 20:47:51.452] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\4087771444.png' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\17556844665536249856.png'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Users\JuanitoCancino\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2021-06-30 20:47:56.369] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\2914514722.jpg' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\12517745414734086144.jpg'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Users\JuanitoCancino\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2021-06-30 20:48:06.208] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\3891692453.png' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\16714691811758571520.png'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Users\JuanitoCancino\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2021-06-30 20:48:07.477] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\2493392554.png' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\10709039475553468416.png'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Users\JuanitoCancino\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2021-06-30 20:48:10.605] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\2503083641.png' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\10750662377281159168.png'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Users\JuanitoCancino\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2021-06-30 20:48:12.441] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
[2021-06-30 20:52:06.632] [info] Started SGDB Manager 0.4.2
[2021-06-30 20:52:07.562] [info] Got Steam path: c:/program files (x86)/steam
[2021-06-30 20:52:07.573] [info] Got Steam user: 81978887
[2021-06-30 20:52:07.584] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
[2021-06-30 21:49:20.489] [info] Started SGDB Manager 0.4.2
[2021-06-30 21:49:21.551] [info] Got Steam path: c:/program files (x86)/steam
[2021-06-30 21:49:21.561] [info] Got Steam user: 81978887
[2021-06-30 21:49:21.566] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356

**Comment by kongomongo** [comment]
you have two errors in there

the `[2021-06-30 20:47:34.111] [info] Import: uplay rejected Error: Could not parse YAML` is same as https://github.com/SteamGridDB/steamgriddb-manager/issues/99

and `[2021-06-30 20:48:06.208] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\81978887\config\grid\3891692453.png' -> 'c:\program files (x86)\steam\userdata\81978887\config\grid\16714691811758571520.png'` is this https://github.com/SteamGridDB/steamgriddb-manager/issues/99#issuecomment-767124567
