### ISSUE TITLE
Infinite loading At the start of the program

### ISSUE THREAD

**Issue by Juanitocancino** [SteamGridDB/steamgriddb-manager#155]
**Describe the bug**
Infinite loading when i start the program, the program let me import games from GOG, Origin and Battlenet
Similar con Issue #123. But the log file that i prove here is more compact (A new and fresh installation)

**To Reproduce**
1.-Install "SteamGridDB Manager" for all users (C:/Program Files/SteamGridDB Manager)
  -This also happened in for the other option (For only one user)
2. Click on 'SteamGridDB Manager.exe' (As Administrator)

**Expected behavior**
Program Starts, but the first loading never stop scanning. If i change to Import it detect the games and let me import games but if i change to Library it get stuck in the infinite loop again.

**Operating System**
 - Windows 10, 1909

**Installed Launchers**
- Steam
- Uplay
- Origins
- GOG
- 

**Screenshots**
![Screenshot 2021-07-03 015138](https://user-images.githubusercontent.com/29244267/124345900-5d82c180-dba1-11eb-82f4-f9108020c406.png)
![Screenshot 2021-07-03 015154](https://user-images.githubusercontent.com/29244267/124345902-5d82c180-dba1-11eb-94f5-9a3027018996.png)

**Log**
[log.log](https://github.com/SteamGridDB/steamgriddb-manager/files/6757959/log.log)

**Additional context**
-Nothing to report

**Comment by kongomongo** [comment]
```
[2021-07-03 01:51:44.472] [info] Import: uplay rejected Error: Could not parse YAML
[2021-07-03 01:52:03.220] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356

```

uplay seems to be the culprit?

**Comment by Juanitocancino** [comment]
> ```
> [2021-07-03 01:51:44.472] [info] Import: uplay rejected Error: Could not parse YAML
> [2021-07-03 01:52:03.220] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
> ```
> 
> uplay seems to be the culprit?

No, it doesn't seems to be the case. I have cleared out the log and launched "SteamGridDB Manager" (As administrator) and then opened the log. In the log files has the following:

[2021-07-07 12:32:05.067] [info] Started SGDB Manager 0.4.2
[2021-07-07 12:32:05.871] [info] Got Steam path: c:/program files (x86)/steam
[2021-07-07 12:32:05.878] [info] Got Steam user: 81978887
[2021-07-07 12:32:05.883] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356

When i go to the import section the following lines are created:

[2021-07-07 12:32:21.524] [info] Import: Started bnet
[2021-07-07 12:32:21.565] [info] Import: Completed bnet
[2021-07-07 12:32:21.566] [info] Import: Started gog
[2021-07-07 12:32:21.717] [info] Import: Completed gog
[2021-07-07 12:32:21.719] [info] Import: Started origin
[2021-07-07 12:32:22.898] [info] Import: Completed origin
[2021-07-07 12:32:22.899] [info] Import: Started uplay
[2021-07-07 12:32:23.099] [info] Import: uplay rejected Error: Could not parse YAML


Note: I also forgot to mention that i have multiple Libraries in Steam (At least 2 libraries in differents HDD). I don't know if that could be a problem.

**Comment by kongomongo** [comment]
Sorry but could you get me the lines surrounding 

`C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356` ?

**Comment by Juanitocancino** [comment]
Of course there is no problem. (I add numbers to the log here on github)

```
3    [2021-07-07 12:32:05.878] [info] Got Steam user: 81978887
4    [2021-07-07 12:32:05.883] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
5        at Function.keys (<anonymous>)
6        at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
7    [2021-07-07 12:32:21.524] [info] Import: Started bnet
8    [2021-07-07 12:32:21.565] [info] Import: Completed bnet
```
i put the new log file here too

[log.log](https://github.com/SteamGridDB/steamgriddb-manager/files/6785594/log.log)

**Comment by kongomongo** [comment]
err, sorry, i meant can you peek into the file 
`C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js`

and copy the lines surrounding 70:41356 where it generates that error?

**Comment by Juanitocancino** [comment]
Sorry

If i open the file with atom `app.asar/public/bundle.js` is completed empty
![appassar](https://user-images.githubusercontent.com/29244267/124989337-a6ed6980-e004-11eb-8cdd-d333af86a22c.png)

but if i open the file with notepad++ it gave me code. i attached the requested lines in a txt (70:41356). 

[appasar as txt.txt](https://github.com/SteamGridDB/steamgriddb-manager/files/6787243/appasar.as.txt.txt)

This is what you need?

**Comment by kongomongo** [comment]
Unfortunately I can't seem to find the referenced line (70:41356) in your attached file... *scratching head*

**Comment by Juanitocancino** [comment]
@kongomongo I have uploaded the file (app.asar) to Mega so you can check it (Maybe i'm not opening correctly)

[https://mega.nz/file/hhJTgQgT#gRJyLoAKyFnhEieNWvIExLDFLNd4A1DecdPpAQ6Z0IE](MEGA Link)

**Comment by isaakfawkes** [comment]
i just started experiencing this error today

**Comment by kongomongo** [comment]
> @kongomongo I have uploaded the file (app.asar) to Mega so you can check it (Maybe i'm not opening correctly)
> 
> [MEGA Link](https://mega.nz/file/okIXTAob#gRJyLoAKyFnhEieNWvIExLDFLNd4A1DecdPpAQ6Z0IE)

Many thanks for your efforts, but I can't seem to find the relevant portion referenced by the error message.

You will have to setup a debugging environment to find the problem I am afraid :(

**Comment by WyntrHeart** [comment]
I'm having this same issue. I tried reinstalling Manager, reinstalling Steam, and running Manager as admin. Import is fully functional for me, but the library tab just loads indefinitely.

**Comment by Juanitocancino** [comment]
@kongomongo i downloaded the repo and run the command `npm install` and then `npm run run`  the output on my cmd (as administrator) was:

> Built at: 07/29/2021 9:51:36 PM
                                   Asset      Size  Chunks                   Chunk Names
                               bundle.js  3.91 MiB    main  [emitted]        main
                           bundle.js.map  4.38 MiB    main  [emitted] [dev]  main
img/39a7c89acf55dcc37e539af6e71110e6.png  9.66 KiB          [emitted]
img/429837590f91f9204ea2b9f73a6c8db2.png   6.2 KiB          [emitted]
img/7b0a89fbd8e80944919607edd1e65bfb.png  7.35 KiB          [emitted]
img/cbecd0dc93ee41852a0edc3d0609facb.png  10.1 KiB          [emitted]
img/cff4ecd83ba2baaafa4bb4acdf885ebb.png  8.58 KiB          [emitted]
Entrypoint main = bundle.js bundle.js.map
[./node_modules/css-loader/dist/cjs.js!./src/css/App.css] 5.14 KiB {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
[./src/css/App.css] 523 bytes {main} [built]
[./src/img/capsule_none.png] 62 bytes {main} [built]
[./src/img/capsule_vertical_none.png] 62 bytes {main} [built]
[./src/img/hero_none.png] 62 bytes {main} [built]
[./src/img/uwp-noise.png] 62 bytes {main} [built]
[./src/js/App.jsx] 8.57 KiB {main} [built]
[./src/js/Components/toastHandler.jsx] 2.88 KiB {main} [built]
[./src/js/Game.jsx] 9.05 KiB {main} [built]
[./src/js/Import.jsx] 19.4 KiB {main} [built]
[./src/js/Search.jsx] 8.13 KiB {main} [built]
[./src/js/Steam.js] 18.1 KiB {main} [built]
[./src/js/games.jsx] 9.02 KiB {main} [built]
[./src/js/index.jsx] 181 bytes {main} [built]
    + 502 hidden modules

> 21:51:36.951 > Started SGDB Manager 0.4.2
Skip checkForUpdatesAndNotify because application is not packed
21:51:38.235 > Got Steam path: c:/program files (x86)/steam
21:51:38.237 > Got Steam user: 81978887
21:51:38.252 > UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Users/JuanitoCancino/Downloads/2021/07/Zip/steamgriddb-manager-master/steamgriddb-manager-master/public/bundle.js:109503:18

Tracking the error in the file Bundle.js the line 109503  `(Object.keys(parsedLibFolders.LibraryFolders).forEach(function (key) {...)`
It's inside of a value (for a function maybe, i don't know) i attach a fragment of the code (109490 to 109544)

[bundle.js.txt](https://github.com/SteamGridDB/steamgriddb-manager/files/6904857/bundle.js.txt)

**Hope you can find something. If there is something else i can do let me know**

**Comment by Terasol** [comment]
I stumbled on this issue some days ago and have some inside on this.
this currently occurs when switching from stable steam to the steam beta. (changing back to the stable steam client doesnt seem to revert that)
the problem is, that the content structure of the "libraryfolders.vdf" has changed slightly.
accessing the paths for the additional libraries now needs libraryfolders[key].path instead of LibraryFolders[key]

added an example for the new structure, if you are still on the stable steam client.
[libraryfolders.vdf](https://github.com/SteamGridDB/steamgriddb-manager/files/6912310/libraryfolders.vdf.txt)

**Comment by Madcore** [comment]
Can confirm what @Terasol said. Until I changed from stable steam to beta, everything worked fine. After the change, and even rolling back to stable, the manager stopped loading library. Looks like Valve changed how the library is managed in some way, because when I returned to stable, I had to reassign the library folders, because steam remove them from library and though I haven't installed anything.

**Comment by WyntrHeart** [comment]
Steam Beta is definitely not the only cause for this problem. The machine which I'm having this problem on is brand new and has only ever had stable Steam installed on it.

**Comment by Juanitocancino** [comment]
Seems that the error radicates on the function `Keys`... I Force the program to load only one library (marking has comment the error part (Line 109503 - 109509) an putting a string in the line 109501 (`libraries.push("G:\\ADATA_SSD"); // Add library folders from libraryfolders.vdf`).

After doing that the program load my 23 games inside that library and can change the images of a game:
![image](https://user-images.githubusercontent.com/29244267/127788697-979c3125-72ba-489d-812a-fd2f85569cd9.png)
![image](https://user-images.githubusercontent.com/29244267/127788741-82a2e645-ebbe-40bc-9d32-c718d59e5633.png)
![image](https://user-images.githubusercontent.com/29244267/127788749-ccc28387-156b-476d-b1de-249159d4b019.png)

It also load the Other games:
![image](https://user-images.githubusercontent.com/29244267/127789353-424d1dd9-356b-4ab9-9e1e-8c46f6c058ca.png)


Note: i change to the beta client a long ago (the last month i returned to the stable version... But when i read the news of the new disc manager in steam change again to the beta channel) and the `libraryfolders.vdf` that were provided by @Terasol have the same structure has mine (Even i am on the beta client)

**Comment by kongomongo** [comment]
If that's truly the cause (I don't use beta steam, whats the benefit?). Only a patch will help
