### ISSUE TITLE
Configure / syntax / ELIFECYCLE error building on Windows 10

### ISSUE THREAD

**Issue by SabreCat** [steamgriddb/steamgriddb-manager#36]
Gave a try at building from source on Windows 10, and ended up with this error output:

```
E:\Git\steamgriddb-manager>npm i

> metrohash@2.6.0 install E:\Git\steamgriddb-manager\node_modules\metrohash
> node-gyp rebuild

E:\Git\steamgriddb-manager\node_modules\metrohash>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\sabre\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Git\steamgriddb-manager\node_modules\metrohash
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metrohash@2.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metrohash@2.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by doZennn** [comment]
Looks like it's having trouble building `node-metrohash`.  
According to this you need to install Python 2.7 https://github.com/robertklep/node-metrohash/issues/12

**Comment by SabreCat** [comment]
Oh boy. OK, I'll give that a go! (Hopefully I can get Python 2.7 to install without completely overriding Python 3.7, which I've struggled with using their Windows installers...)
