### ISSUE TITLE
Game import not working

### ISSUE THREAD

**Issue by Anegus** [steamgriddb/steamgriddb-manager#39]
When I click "Import games" button the loading circle just keeps spinning. Installed first time on version 0.2.6, been like this since.

I checked log file and it's stuck after "Fetched 62 Steam games". Before I added 1 game it was 61. Probably certain Steam game that's incompatible?

**Comment by doZennn** [comment]
Did you try on version v0.3.0?

**Comment by Anegus** [comment]
Yes

**Comment by doZennn** [comment]
Update to v0.3.1 and try again please.

**Comment by josask** [comment]
[2019-09-09 21:56:57.561] [error] UnhandledRejection TypeError: this.games.map is not a function
    at t.value (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:74938)
    at ma (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:65520)
    at ya (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:65315)
    at ql (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:99598)
    at zl (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:84005)
    at Fl (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:81032)
    at Al (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:79605)
    at file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:41756
    at t.unstable_runWithPriority (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:51:3878)
    at uo (file:///C:/Users/User/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:41485)

**Comment by Anegus** [comment]
Still nothing.

[2019-09-09 22:18:16.491] [info] Started SGDB Manager 0.3.1
[2019-09-09 22:18:17.357] [info] Got Steam path: c:/program files (x86)/steam
[2019-09-09 22:18:17.371] [info] Got Steam user: 265707104
[2019-09-09 22:18:17.376] [info] Got Steam user: 265707104
[2019-09-09 22:18:17.389] [info] Found 2 Steam libraries
[2019-09-09 22:18:18.527] [info] Fetched 61 Steam games

**Comment by Anegus** [comment]
v 0.3.6 fixed the problem
