### ISSUE TITLE
Infinite loading, import not working

### ISSUE THREAD

**Issue by Sotaur** [steamgriddb/steamgriddb-manager#56]
From a fresh install, when I open it up the spinning wheel never stops. When I go to import it will show all of the games, but clicking import doesn't work. Here's the log file contents: 
[2019-11-08 07:17:03.712] [info] Started SGDB Manager 0.3.6
[2019-11-08 07:17:04.898] [info] Got Steam path: c:/program files (x86)/steam
[2019-11-08 07:17:28.357] [info] Import: Started bnet
[2019-11-08 07:17:28.363] [info] Import: Started egs
[2019-11-08 07:17:28.371] [info] Import: Started gog
[2019-11-08 07:17:28.396] [info] Import: Completed bnet
[2019-11-08 07:17:28.419] [info] Import: Completed egs
[2019-11-08 07:17:28.425] [info] Import: Completed gog
[2019-11-08 07:17:28.430] [info] Import: 2 games found for bnet
[2019-11-08 07:17:28.434] [info] s1,s2
[2019-11-08 07:17:28.441] [info] Import: 3 games found for egs
[2019-11-08 07:17:28.445] [info] Feverfew,Eagle,Turaco
[2019-11-08 07:17:28.450] [info] Import: 0 games found for gog
[2019-11-08 07:17:28.454] [info] Import: origin not installed
[2019-11-08 07:17:28.459] [info] Import: uplay not installed
[2019-11-08 07:17:31.324] [error] TypeError: Cannot read property '0' of undefined
    at file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:81718
    at Array.forEach (<anonymous>)
    at t.value (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:81665)
    at t.value (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:77125)
    at Object.<anonymous> (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1152)
    at w (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1190)
    at file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1336
    at S (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1422)
    at E (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1871)
    at C (file:///C:/Users/chris/AppData/Local/Programs/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1683)
[2019-11-18 16:52:53.982] [info] Started SGDB Manager 0.3.6
[2019-11-18 16:52:55.533] [info] Got Steam path: c:/program files (x86)/steam
[2019-11-18 16:53:43.127] [info] Import: Started bnet
[2019-11-18 16:53:43.136] [info] Import: Started egs
[2019-11-18 16:53:43.144] [info] Import: Started gog
[2019-11-18 16:53:43.177] [info] Import: Completed bnet
[2019-11-18 16:53:43.203] [info] Import: Completed egs
[2019-11-18 16:53:43.209] [info] Import: Completed gog
[2019-11-18 16:53:43.215] [info] Import: 2 games found for bnet
[2019-11-18 16:53:43.221] [info] s1,s2
[2019-11-18 16:53:43.229] [info] Import: 3 games found for egs
[2019-11-18 16:53:43.234] [info] Feverfew,Eagle,Turaco
[2019-11-18 16:53:43.240] [info] Import: 0 games found for gog
[2019-11-18 16:53:43.245] [info] Import: origin not installed
[2019-11-18 16:53:43.251] [info] Import: uplay not installed
[2019-11-18 16:55:07.361] [info] Import: Started bnet
[2019-11-18 16:55:07.370] [info] Import: Started egs
[2019-11-18 16:55:07.379] [info] Import: Started gog
[2019-11-18 16:55:07.399] [info] Import: Completed bnet
[2019-11-18 16:55:07.409] [info] Import: Completed egs
[2019-11-18 16:55:07.437] [info] Import: Completed gog
[2019-11-18 16:55:07.443] [info] Import: 2 games found for bnet
[2019-11-18 16:55:07.448] [info] s1,s2

The import statements show up every time, but the error has only happened once.

**Comment by Sotaur** [comment]
Also, what version of node should this be built with?

**Comment by Schellboy** [comment]
Same problem here with a fresh install today :-/
Nothing happens when i click on import and the libary show me nothing and the spinning wheel nevver stops too.

[2019-11-21 09:53:50.533] [info] Started SGDB Manager 0.3.6
[2019-11-21 09:53:51.343] [info] Got Steam path: e:/steam
[2019-11-21 09:54:15.521] [info] Import: Started origin
[2019-11-21 09:54:15.765] [info] Import: Completed origin
[2019-11-21 09:54:15.774] [info] Import: bnet not installed
[2019-11-21 09:54:15.781] [info] Import: egs not installed
[2019-11-21 09:54:15.787] [info] Import: gog not installed
[2019-11-21 09:54:15.793] [info] Import: 3 games found for origin
[2019-11-21 09:54:15.798] [info] Origin.OFR.50.0002942,Origin.OFR.50.0003453,Origin.OFR.50.0003514
[2019-11-21 09:54:15.810] [info] Import: uplay not installed

**Comment by SolidSnake4** [comment]
**Same here**

**Comment by gigq** [comment]
Same issue here, also trying older versions results in the same problem.

**Comment by Sotaur** [comment]
It must be some update to Steam's APIs that broke this if older versions also break.

**Comment by dus10lee** [comment]
its strange because it works fine on my laptop but not my desktop with the same version of steam

**Comment by doZennn** [comment]
Sorry for the delays, can you guys try with v0.4.0?

**Comment by Supavitax** [comment]
> 
> 
> Sorry for the delays, can you guys try with v0.4.0?

Just tested it but same thing is happening.

**Comment by barryjj** [comment]
> > Sorry for the delays, can you guys try with v0.4.0?
> 
> Just tested it but same thing is happening.

Same thing here. 

I wonder if it's got to do with the size of the library on initial import... How big are your libraries?  I left it running from for about 5 hours while the system was pretty much idle and still just had the spinning load icon in the application window.  It certainly seems like it could be that the code is making too many API calls in a short amount of time and being temporarily blacklisted from hitting the API again.  This used to happen with Enhanced Steam (before it was forked into Augmented Steam) when you would navigate to the market page and it would be making API calls to Valve in order to query the buy and sell orders for cards.

**Comment by Schellboy** [comment]
Unfortunately no improvement.
Here is the log:
[2019-12-03 14: 16: 50.267] [info] Got Steam path: c: / program files (x86) / steam
[2019-12-03 14: 16: 50.278] [info] Found 2 Steam libraries
[2019-12-03 14: 16: 50.298] [info] Fetched 4 Steam games
[2019-12-03 14: 18: 16.307] [info] Import: Started origin
[2019-12-03 14: 18: 16.515] [info] Import: Completed origin

The libraries are found, but in the manager is still spinningwheel and an import does not work even though it appears in the logfile as "completed". If any data is needed ask quietly. Thank you!

**Comment by Supavitax** [comment]
> 
> 
> > > Sorry for the delays, can you guys try with v0.4.0?
> > 
> > 
> > Just tested it but same thing is happening.
> 
> Same thing here.
> 
> I wonder if it's got to do with the size of the library on initial import... How big are your libraries? I left it running from for about 5 hours while the system was pretty much idle and still just had the spinning load icon in the application window. It certainly seems like it could be that the code is making too many API calls in a short amount of time and being temporarily blacklisted from hitting the API again. This used to happen with Enhanced Steam (before it was forked into Augmented Steam) when you would navigate to the market page and it would be making API calls to Valve in order to query the buy and sell orders for cards.

I only have around 20 actually installed and I left it running for about 2 hours but nothing changed.

**Comment by barryjj** [comment]
> > > > Sorry for the delays, can you guys try with v0.4.0?
> > > 
> > > 
> > > Just tested it but same thing is happening.
> > 
> > 
> > Same thing here.
> > I wonder if it's got to do with the size of the library on initial import... How big are your libraries? I left it running from for about 5 hours while the system was pretty much idle and still just had the spinning load icon in the application window. It certainly seems like it could be that the code is making too many API calls in a short amount of time and being temporarily blacklisted from hitting the API again. This used to happen with Enhanced Steam (before it was forked into Augmented Steam) when you would navigate to the market page and it would be making API calls to Valve in order to query the buy and sell orders for cards.
> 
> I only have around 20 actually installed and I left it running for about 2 hours but nothing changed.

Does it only query installed games or does it query your entire library? I'm guessing the latter (much like the GOG Galaxy 2.0 beta, which chugged on initial import of my Steam library but is much better now only looking for the delta).  If it's the former, I'm out of ideas.  How big is your Steam library overall?

**Comment by Supavitax** [comment]
> 
> 
> > > > > Sorry for the delays, can you guys try with v0.4.0?
> > > > 
> > > > 
> > > > Just tested it but same thing is happening.
> > > 
> > > 
> > > Same thing here.
> > > I wonder if it's got to do with the size of the library on initial import... How big are your libraries? I left it running from for about 5 hours while the system was pretty much idle and still just had the spinning load icon in the application window. It certainly seems like it could be that the code is making too many API calls in a short amount of time and being temporarily blacklisted from hitting the API again. This used to happen with Enhanced Steam (before it was forked into Augmented Steam) when you would navigate to the market page and it would be making API calls to Valve in order to query the buy and sell orders for cards.
> > 
> > 
> > I only have around 20 actually installed and I left it running for about 2 hours but nothing changed.
> 
> Does it only query installed games or does it query your entire library? I'm guessing the latter (much like the GOG Galaxy 2.0 beta, which chugged on initial import of my Steam library but is much better now only looking for the delta). If it's the former, I'm out of ideas. How big is your Steam library overall?

Looking at the code it only appears to query what's installed rather than the entire library. I have about 500 games but only around 20 installed.

**Comment by Supavitax** [comment]
I've just been having a look at the code and when I change

> Promise.all([steamGamesPromise, nonSteamGamesPromise]).then((values) => {

to

> Promise.all([steamGamesPromise]).then((values) => {

from **fetchGames()** in **games.jsx** it loads my installed Steam games instantly. 

[https://i.postimg.cc/Qd8ndktG/img.jpg](url)

**Comment by doZennn** [comment]
Should be fixed in [v0.4.1](https://github.com/steamgriddb/steamgriddb-manager/releases/tag/v0.4.1)

**Comment by Schellboy** [comment]
THX. Now is running 👍

**Comment by SolidSnake4** [comment]
it's working now, Thanks 🙏

**Comment by xfechx** [comment]
I am having this issue at the moment. All of the sudden, I can no longer view my library, it is loading infinitely. I have tried uninstalling and re-installing, without success.
