### ISSUE TITLE
No images for Origin based games, wheel keeps spinning (v0.4.2) - Windows

### ISSUE THREAD

**Issue by susobhang70** [steamgriddb/steamgriddb-manager#64]
I apologize if I'm missing something, but I see that issue #60 has resurfaced for Origin Games. I do not see any images/previews for FIFA 20 or Star Wars: Jedi Fallen Order. Please look below for screenshots for same. I'm on v0.4.2 version of the app, on Windows 10. No images after importing to Steam Library. PFA the log as well. Please let me know if you need any additional information. Thank you!

`[2019-12-24 05:08:30.982] [info] Started SGDB Manager 0.4.2`
`[2019-12-24 05:08:31.698] [info] Got Steam path: c:/program files (x86)/steam`
`[2019-12-24 05:08:31.706] [info] Found 1 Steam libraries`
`[2019-12-24 05:08:31.709] [info] Fetched 5 Steam games`
`[2019-12-24 05:08:31.710] [info] Got Steam user: 113217334`
`[2019-12-24 05:08:42.576] [info] Import: Started bnet`
`[2019-12-24 05:08:42.612] [info] Import: Completed bnet`
`[2019-12-24 05:08:42.613] [info] Import: Started egs`
`[2019-12-24 05:08:42.632] [info] Import: Started origin`
`[2019-12-24 05:08:42.754] [info] Import: Completed origin`
`[2019-12-24 05:08:55.219] [info] Found 1 Steam libraries`
`[2019-12-24 05:08:55.221] [info] Fetched 5 Steam games`
`[2019-12-24 05:08:59.383] [error] UnhandledRejection Error: Game not found`
`    at C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\steamgriddb\src\SGDB.js:56:37`
`    at processTicksAndRejections (internal/process/task_queues.js:89:5)`

![image](https://user-images.githubusercontent.com/10455026/71380502-6983df80-260a-11ea-8df5-2d0edf01ca36.png)

![image](https://user-images.githubusercontent.com/10455026/71380543-93d59d00-260a-11ea-8a6b-3d9d1bac098c.png)

![image](https://user-images.githubusercontent.com/10455026/71380554-9df79b80-260a-11ea-93e8-71b926dd8b99.png)

**Comment by sysmoon14** [comment]
I get this issue too
