### ISSUE TITLE
"A JavaScript error occurred in the renderer process"

### ISSUE THREAD

**Issue by randybruder** [steamgriddb/steamgriddb-manager#79]
**Describe the bug**

When trying to import games, I get stuck on Uplay and get an error message (that when dismissing with the 'Ok' button immediately reappears, and requires force quitting SteamGridDB Manager.)

```
TypeError: Cannot read property 'value' of null
   at
file:///C:/Users/Shadow/AppData/Local/Programs/SteamGridDB%20Manager/resour…:434713
   at ChildProcess. <anonymous> (C:\Users\Shadow\AppData\Local\Programs\SteamGridDB Manager\resources\app.asar\node_modules\winreg\lib\registry.js:632:7)
   at ChildProcess.emit (events.js:200:13)
   at maybeClose (internal/child_process.js:1021:16)
   at Socket. <anonymous> (internal/child_process.js:430:11)
   at Sockt.emit (events.js:200:13)
   at Pipe. <anonymous> (net.js:586:12)
```

**To Reproduce**
1. Launch SteamGridDB Manager
2. Click on 'Import Games'

**Operating System**
 - Windows 10, 1909

**Installed Launchers**
- Epic Games Launcher
- Uplay
- Origin
- Blizzard Battle.net

**Screenshots**
<img width="1680" alt="Screenshot of the error message" src="https://user-images.githubusercontent.com/6447487/77690951-7d790d80-6f7a-11ea-886f-7412e300e9b5.png">

**Log**
[log.log](https://github.com/steamgriddb/steamgriddb-manager/files/4389667/log.log)

**Comment by vgarcia007** [comment]
Exact same Probleme here, When scanning Uplay Titles.

**Comment by vgarcia007** [comment]
I looked at the Uplay Importer.

on my System Uplay is installed.

class Uplay  static isInstalled():

This is looking for a Uplay Installation by checking the Key for Uninstaller.

`key: '\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Uplay',`

This REG Key dosen´t exists on my Machine, although Uplay is installed.

It should throw the Error "Could not check if Uplay is installed." but it dosen´t.

class Uplay getUplayPath():

This iterates throu Elemets to find the install Path.
`key: '\\SOFTWARE\\Ubisoft\\Launcher',`
In none of the values or childs is the path to the Launcher (on my Machine)

@randybruder Can you check your registry for the Keys and look if they exists, please?

**Comment by aranel616** [comment]
Like @vgarcia007 said, this is related to finding the Uplay path from the registry. However, I don't think it's from `isInstalled`, as that does not access `.value` of anything. It's more likely from `getUplayPath`, when looping through registry items to check the value of `InstallDir`. It could also be coming from `_processRegKey`, or `resolveConfigPath`, the two other functions that check `.value` of something.

It appears that when looking through the registry, if any registry item does not have a value, it would cause this error to occur.
