### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Hardennest** [SteamGridDB/steamgriddb-manager#99]
When I first downloaded it, it was fine, but then I change my steam account so I need to import it again, but this time it has infinite loading screen, I tried to reinstall it but it's still the same

My error
1. Open steamgriddb
2.then it's just infinite loading (also can't import)

Operating system
 - Windows 10

Installed Launchers
- Epic Games Launcher
- Uplay
Log
[2020-09-29 18:12:33.161] [info] Started SGDB Manager 0.4.2
[2020-09-29 18:12:39.094] [info] Got Steam path: c:/program files (x86)/steam
[2020-09-29 18:12:39.123] [info] Found 1 Steam libraries
[2020-09-29 18:12:39.128] [info] Fetched 1 Steam games
[2020-09-29 18:12:39.134] [info] Got Steam user: 1075249034
[2020-09-29 18:12:46.145] [info] Import: Started egs
[2020-09-29 18:12:46.289] [info] Import: Completed egs
[2020-09-29 18:12:46.293] [info] Import: Started uplay
[2020-09-29 18:12:47.052] [info] Found 1 Steam libraries
[2020-09-29 18:12:47.059] [info] Fetched 1 Steam games
[2020-09-29 18:12:47.172] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-09-29 18:12:47.173] [info] Import: Completed uplay
[2020-09-29 18:12:50.310] [info] Import: Started egs
[2020-09-29 18:12:50.562] [info] Import: Completed egs
[2020-09-29 18:12:50.565] [info] Import: Started uplay
[2020-09-29 18:12:51.751] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-09-29 18:12:51.752] [info] Import: Completed uplay
[2020-09-29 18:13:35.356] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\1075249034\config\grid\3290742411.png' -> 'c:\program files (x86)\steam\userdata\1075249034\config\grid\14133631034838745088.png'
    at Object.symlinkSync (fs.js:935:3)
    at Function.lnf [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\lnf\lib\index.js:63:20)
    at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71361
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Promise.all (index 0)
[2020-09-29 18:15:00.855] [info] Started SGDB Manager 0.4.2
[2020-09-30 12:26:26.021] [info] Started SGDB Manager 0.4.2
[2020-09-30 12:26:29.909] [info] Got Steam path: c:/program files (x86)/steam
[2020-09-30 12:26:29.945] [info] Found 1 Steam libraries
[2020-09-30 12:26:29.964] [info] Fetched 1 Steam games
[2020-09-30 12:26:30.001] [info] Got Steam user: 1075249034
[2020-09-30 12:26:43.179] [info] Import: Started egs
[2020-09-30 12:26:43.369] [info] Import: Completed egs
[2020-09-30 12:26:43.419] [info] Import: Started uplay
[2020-09-30 12:26:44.947] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-09-30 12:26:44.951] [info] Import: Completed uplay
[2020-10-04 19:26:23.656] [info] Started SGDB Manager 0.4.2
[2020-10-04 19:26:28.372] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-04 19:26:28.416] [info] Found 1 Steam libraries
[2020-10-04 19:26:28.421] [info] Fetched 0 Steam games
[2020-10-04 19:26:28.429] [info] Got Steam user: 1075249034
[2020-10-04 19:26:51.746] [info] Import: Started egs
[2020-10-04 19:26:51.990] [info] Import: Completed egs
[2020-10-04 19:26:51.994] [info] Import: Started uplay
[2020-10-04 19:26:53.306] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-04 19:26:53.312] [info] Import: Completed uplay
[2020-10-04 19:27:02.526] [error] Error: EBUSY: resource busy or locked, rename 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json.2751504917' -> 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:179:20)
    at ElectronStore.set store [as store] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:449:8)
    at ElectronStore.set (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:327:14)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70018)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70251)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71979)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:61662)
    at Object.<anonymous> (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1126)
[2020-10-06 10:24:06.746] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:24:10.390] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:24:10.422] [info] Found 1 Steam libraries
[2020-10-06 10:24:10.426] [info] Fetched 0 Steam games
[2020-10-06 10:24:17.763] [info] Import: Started egs
[2020-10-06 10:24:17.910] [info] Import: Completed egs
[2020-10-06 10:24:17.913] [info] Import: Started uplay
[2020-10-06 10:24:18.743] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:24:18.745] [info] Import: Completed uplay
[2020-10-06 10:25:01.170] [info] Found 1 Steam libraries
[2020-10-06 10:25:01.173] [info] Fetched 0 Steam games
[2020-10-06 10:25:23.042] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:25:26.366] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:25:26.391] [info] Found 1 Steam libraries
[2020-10-06 10:25:26.395] [info] Fetched 0 Steam games
[2020-10-06 10:26:53.312] [info] Import: Started egs
[2020-10-06 10:26:53.687] [info] Import: Completed egs
[2020-10-06 10:26:53.691] [info] Import: Started uplay
[2020-10-06 10:26:54.682] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:26:54.685] [info] Import: Completed uplay
[2020-10-06 10:26:59.520] [error] Error: EBUSY: resource busy or locked, rename 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json.694507570' -> 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:179:20)
    at ElectronStore.set store [as store] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:449:8)
    at ElectronStore.set (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:327:14)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70018)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70251)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71979)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:61662)
    at Object.<anonymous> (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1126)
[2020-10-06 10:27:14.036] [info] Found 1 Steam libraries
[2020-10-06 10:27:14.040] [info] Fetched 0 Steam games
[2020-10-06 10:27:16.372] [info] Import: Started egs
[2020-10-06 10:27:16.559] [info] Import: Completed egs
[2020-10-06 10:27:16.564] [info] Import: Started uplay
[2020-10-06 10:27:17.908] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:27:17.911] [info] Import: Completed uplay
[2020-10-06 10:28:11.038] [info] Found 1 Steam libraries
[2020-10-06 10:28:11.041] [info] Fetched 0 Steam games
[2020-10-06 10:28:15.043] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:28:18.507] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:28:18.548] [info] Found 1 Steam libraries
[2020-10-06 10:28:18.552] [info] Fetched 0 Steam games
[2020-10-06 10:28:35.281] [info] Import: Started egs
[2020-10-06 10:28:35.390] [info] Import: Completed egs
[2020-10-06 10:28:35.394] [info] Import: Started uplay
[2020-10-06 10:28:36.111] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:28:36.114] [info] Import: Completed uplay
[2020-10-06 10:28:52.381] [error] Error: EBUSY: resource busy or locked, rename 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json.542522399' -> 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:179:20)
    at ElectronStore.set store [as store] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:449:8)
    at ElectronStore.set (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:327:14)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70018)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70251)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71979)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:61662)
    at Object.<anonymous> (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1126)
[2020-10-06 10:29:25.423] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:29:30.788] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:29:30.878] [info] Found 1 Steam libraries
[2020-10-06 10:29:30.901] [info] Fetched 0 Steam games
[2020-10-06 10:30:15.857] [info] Import: Started egs
[2020-10-06 10:30:16.098] [info] Import: Completed egs
[2020-10-06 10:30:16.102] [info] Import: Started uplay
[2020-10-06 10:30:17.182] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:30:17.190] [info] Import: Completed uplay
[2020-10-06 10:30:27.807] [info] Found 1 Steam libraries
[2020-10-06 10:30:27.810] [info] Fetched 0 Steam games
[2020-10-06 10:31:01.956] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:31:05.019] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:31:05.051] [info] Found 1 Steam libraries
[2020-10-06 10:31:05.061] [info] Fetched 0 Steam games
[2020-10-06 10:32:05.746] [info] Import: Started egs
[2020-10-06 10:32:06.034] [info] Import: Completed egs
[2020-10-06 10:32:06.038] [info] Import: Started uplay
[2020-10-06 10:32:06.754] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:32:06.757] [info] Import: Completed uplay
[2020-10-06 10:32:20.978] [info] Found 1 Steam libraries
[2020-10-06 10:32:20.981] [info] Fetched 0 Steam games
[2020-10-06 10:36:25.810] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:36:29.231] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:36:29.254] [info] Found 1 Steam libraries
[2020-10-06 10:36:29.259] [info] Fetched 0 Steam games
[2020-10-06 10:37:50.706] [info] Import: Started egs
[2020-10-06 10:37:50.882] [info] Import: Completed egs
[2020-10-06 10:37:50.888] [info] Import: Started uplay
[2020-10-06 10:37:51.805] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:37:51.808] [info] Import: Completed uplay
[2020-10-06 10:38:13.799] [info] Found 1 Steam libraries
[2020-10-06 10:38:13.802] [info] Fetched 0 Steam games
[2020-10-06 10:41:46.908] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:41:50.554] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:41:50.579] [info] Found 1 Steam libraries
[2020-10-06 10:41:50.583] [info] Fetched 0 Steam games
[2020-10-06 10:43:30.032] [info] Import: Started egs
[2020-10-06 10:43:30.274] [info] Import: Completed egs
[2020-10-06 10:43:30.287] [info] Import: Started uplay
[2020-10-06 10:43:30.998] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-06 10:43:31.004] [info] Import: Completed uplay
[2020-10-06 10:43:57.584] [error] Error: EBUSY: resource busy or locked, rename 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json.2398535329' -> 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:179:20)
    at ElectronStore.set store [as store] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:449:8)
    at ElectronStore.set (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:327:14)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70018)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70251)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71979)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:61662)
    at Object.<anonymous> (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1126)
[2020-10-06 10:47:52.881] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:48:53.727] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:49:02.463] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:49:02.506] [info] Found 1 Steam libraries
[2020-10-06 10:49:02.510] [info] Fetched 0 Steam games
[2020-10-06 10:50:50.160] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:50:56.901] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:50:56.948] [info] Found 1 Steam libraries
[2020-10-06 10:50:56.965] [info] Fetched 0 Steam games
[2020-10-06 10:52:43.540] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:52:47.388] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:52:47.421] [info] Found 1 Steam libraries
[2020-10-06 10:52:47.439] [info] Fetched 0 Steam games
[2020-10-06 10:54:01.548] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:54:06.850] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:54:06.889] [info] Found 1 Steam libraries
[2020-10-06 10:54:06.893] [info] Fetched 0 Steam games
[2020-10-06 10:58:59.457] [info] Started SGDB Manager 0.4.2
[2020-10-06 10:59:07.570] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 10:59:07.668] [info] Found 1 Steam libraries
[2020-10-06 10:59:07.675] [info] Fetched 0 Steam games
[2020-10-06 11:00:39.994] [info] Started SGDB Manager 0.4.2
[2020-10-06 11:00:44.587] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-06 11:00:44.643] [info] Found 1 Steam libraries
[2020-10-06 11:00:44.647] [info] Fetched 0 Steam games
[2020-10-07 07:47:55.411] [info] Started SGDB Manager 0.4.2
[2020-10-07 07:48:07.093] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-07 07:48:07.136] [info] Found 1 Steam libraries
[2020-10-07 07:48:07.167] [info] Fetched 1 Steam games
[2020-10-07 07:50:01.393] [info] Import: Started egs
[2020-10-07 07:50:01.605] [info] Import: Completed egs
[2020-10-07 07:50:01.610] [info] Import: Started uplay
[2020-10-07 07:50:02.706] [info] Found 1 Steam libraries
[2020-10-07 07:50:02.712] [info] Fetched 1 Steam games
[2020-10-07 07:50:02.951] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-07 07:50:02.956] [info] Import: Completed uplay
[2020-10-07 07:53:21.789] [info] Started SGDB Manager 0.4.2
[2020-10-07 07:53:22.676] [info] Started SGDB Manager 0.4.2
[2020-10-07 07:53:28.648] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-07 07:53:28.685] [info] Found 1 Steam libraries
[2020-10-07 07:53:28.700] [info] Fetched 1 Steam games
[2020-10-07 07:53:28.847] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-07 07:53:28.876] [info] Found 1 Steam libraries
[2020-10-07 07:53:28.887] [info] Fetched 1 Steam games
[2020-10-07 07:56:47.174] [info] Started SGDB Manager 0.4.2
[2020-10-07 07:56:51.944] [info] Got Steam path: c:/program files (x86)/steam
[2020-10-07 07:56:51.996] [info] Found 1 Steam libraries
[2020-10-07 07:56:52.003] [info] Fetched 1 Steam games
[2020-10-07 07:58:11.881] [info] Import: Started egs
[2020-10-07 07:58:12.098] [info] Import: Completed egs
[2020-10-07 07:58:12.102] [info] Import: Started uplay
[2020-10-07 07:58:13.192] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-07 07:58:13.197] [info] Import: Completed uplay
[2020-10-07 07:58:16.130] [info] Found 1 Steam libraries
[2020-10-07 07:58:16.135] [info] Fetched 1 Steam games
[2020-10-07 07:58:19.480] [info] Import: Started egs
[2020-10-07 07:58:19.881] [info] Import: Completed egs
[2020-10-07 07:58:19.884] [info] Import: Started uplay
[2020-10-07 07:58:21.025] [info] Import: uplay - Could not resolve executable for Tom Clancy's Rainbow Six Siege
[2020-10-07 07:58:21.029] [info] Import: Completed uplay
[2020-10-07 07:59:07.055] [error] Error: EBUSY: resource busy or locked, rename 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json.3725802254' -> 'C:\Users\USER\AppData\Roaming\steamgriddb-manager\config.json'
    at Object.renameSync (fs.js:609:3)
    at Function.writeFileSync [as sync] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\node_modules\write-file-atomic\index.js:200:8)
    at ElectronStore._write (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:179:20)
    at ElectronStore.set store [as store] (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:449:8)
    at ElectronStore.set (C:\Program Files\SteamGridDB Manager\resources\app.asar\node_modules\conf\index.js:327:14)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70018)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:70251)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:71979)
    at t.value (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:61662)
    at Object.<anonymous> (file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:43:1126)
Help me please

**Comment by aranel616** [comment]
I'm not sure why, but your config file for the app can't be accessed, so the app is freezing when trying to get your non-Steam games. 

I'd like to look more into why this is happening, but in the meantime, try opening `%APPDATA%/steamgriddb-manager` (you can do this by pressing `WIN+R` and then pasting it in and hitting enter), and then deleting the `config.json` file. See if it works after that.

**Comment by OneGunBullet** [comment]
https://github.com/steamgriddb/steamgriddb-manager/issues/56

Are these two issues the same?

**Comment by kongomongo** [comment]
This also means SGDB-Manager is run without admin privileges

```
[2020-09-29 18:13:35.356] [error] UnhandledRejection Error: EPERM: operation not permitted, symlink 'c:\program files (x86)\steam\userdata\1075249034\config\grid\3290742411.png' -> 'c:\program files (x86)\steam\userdata\1075249034\config\grid\14133631034838745088.png'
at Object.symlinkSync (fs.js:935:3)

```

**Comment by aranel616** [comment]
The next version no longer uses symlinks for this, so this will not be an
issue soon.

**Comment by Men1steR** [comment]
[2021-07-02 09:44:38.999] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356

Hello, how can i fix it?

**Comment by kongomongo** [comment]
> [2021-07-02 09:44:38.999] [error] UnhandledRejection TypeError: Cannot convert undefined or null to object
> at Function.keys ()
> at file:///C:/Program%20Files/SteamGridDB%20Manager/resources/app.asar/public/bundle.js:70:41356
> 
> Hello, how can i fix it?

same issue as https://github.com/SteamGridDB/steamgriddb-manager/issues/155
